/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Item = IDL.Record({
  'qty' : IDL.Nat,
  'itemName' : IDL.Text,
  'remarks' : IDL.Text,
  'condition' : IDL.Text,
});
export const InventoryChecklist = IDL.Record({
  'id' : IDL.Nat,
  'ownerName' : IDL.Text,
  'date' : IDL.Text,
  'propertyId' : IDL.Nat,
  'tenantName' : IDL.Text,
  'items' : IDL.Vec(Item),
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'clientName' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'propertyId' : IDL.Nat,
  'invoiceNumber' : IDL.Text,
  'paymentMode' : IDL.Text,
  'amount' : IDL.Nat,
});
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'contact' : IDL.Text,
  'ownerName' : IDL.Text,
  'propertyType' : IDL.Text,
  'rentCommission' : IDL.Nat,
  'city' : IDL.Text,
  'deposit' : IDL.Nat,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'saleCommission' : IDL.Nat,
  'expectedPrice' : IDL.Nat,
  'expectedRent' : IDL.Nat,
  'dealType' : IDL.Text,
});
export const SiteVisit = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'clientName' : IDL.Text,
  'visitDate' : IDL.Text,
  'propertyId' : IDL.Nat,
  'requirementType' : IDL.Text,
  'budget' : IDL.Nat,
  'remarks' : IDL.Text,
});

export const idlService = IDL.Service({
  'addInventoryChecklist' : IDL.Func([InventoryChecklist], [IDL.Nat], []),
  'addInvoice' : IDL.Func([Invoice], [IDL.Text], []),
  'addProperty' : IDL.Func([Property], [IDL.Nat], []),
  'addSiteVisit' : IDL.Func([SiteVisit], [IDL.Nat], []),
  'deleteInventoryChecklist' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'deleteSiteVisit' : IDL.Func([IDL.Nat], [], []),
  'getAllInventoryChecklists' : IDL.Func([], [IDL.Vec(InventoryChecklist)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getAllSiteVisits' : IDL.Func([], [IDL.Vec(SiteVisit)], ['query']),
  'getDefaultChecklistItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getInventoryChecklist' : IDL.Func([IDL.Nat], [InventoryChecklist], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
  'getSiteVisit' : IDL.Func([IDL.Nat], [SiteVisit], ['query']),
  'updateInventoryChecklist' : IDL.Func([InventoryChecklist], [], []),
  'updateInvoice' : IDL.Func([Invoice], [], []),
  'updateProperty' : IDL.Func([Property], [], []),
  'updateSiteVisit' : IDL.Func([SiteVisit], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Item = IDL.Record({
    'qty' : IDL.Nat,
    'itemName' : IDL.Text,
    'remarks' : IDL.Text,
    'condition' : IDL.Text,
  });
  const InventoryChecklist = IDL.Record({
    'id' : IDL.Nat,
    'ownerName' : IDL.Text,
    'date' : IDL.Text,
    'propertyId' : IDL.Nat,
    'tenantName' : IDL.Text,
    'items' : IDL.Vec(Item),
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'clientName' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'propertyId' : IDL.Nat,
    'invoiceNumber' : IDL.Text,
    'paymentMode' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'contact' : IDL.Text,
    'ownerName' : IDL.Text,
    'propertyType' : IDL.Text,
    'rentCommission' : IDL.Nat,
    'city' : IDL.Text,
    'deposit' : IDL.Nat,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'saleCommission' : IDL.Nat,
    'expectedPrice' : IDL.Nat,
    'expectedRent' : IDL.Nat,
    'dealType' : IDL.Text,
  });
  const SiteVisit = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'clientName' : IDL.Text,
    'visitDate' : IDL.Text,
    'propertyId' : IDL.Nat,
    'requirementType' : IDL.Text,
    'budget' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  
  return IDL.Service({
    'addInventoryChecklist' : IDL.Func([InventoryChecklist], [IDL.Nat], []),
    'addInvoice' : IDL.Func([Invoice], [IDL.Text], []),
    'addProperty' : IDL.Func([Property], [IDL.Nat], []),
    'addSiteVisit' : IDL.Func([SiteVisit], [IDL.Nat], []),
    'deleteInventoryChecklist' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'deleteSiteVisit' : IDL.Func([IDL.Nat], [], []),
    'getAllInventoryChecklists' : IDL.Func([], [IDL.Vec(InventoryChecklist)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getAllSiteVisits' : IDL.Func([], [IDL.Vec(SiteVisit)], ['query']),
    'getDefaultChecklistItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getInventoryChecklist' : IDL.Func([IDL.Nat], [InventoryChecklist], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
    'getSiteVisit' : IDL.Func([IDL.Nat], [SiteVisit], ['query']),
    'updateInventoryChecklist' : IDL.Func([InventoryChecklist], [], []),
    'updateInvoice' : IDL.Func([Invoice], [], []),
    'updateProperty' : IDL.Func([Property], [], []),
    'updateSiteVisit' : IDL.Func([SiteVisit], [], []),
  });
};

export const init = ({ IDL }) => { return []; };