/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface InventoryChecklist {
  'id' : bigint,
  'ownerName' : string,
  'date' : string,
  'propertyId' : bigint,
  'tenantName' : string,
  'items' : Array<Item>,
}
export interface Invoice {
  'id' : bigint,
  'status' : string,
  'clientName' : string,
  'date' : string,
  'description' : string,
  'propertyId' : bigint,
  'invoiceNumber' : string,
  'paymentMode' : string,
  'amount' : bigint,
}
export interface Item {
  'qty' : bigint,
  'itemName' : string,
  'remarks' : string,
  'condition' : string,
}
export interface Property {
  'id' : bigint,
  'title' : string,
  'contact' : string,
  'ownerName' : string,
  'propertyType' : string,
  'rentCommission' : bigint,
  'city' : string,
  'deposit' : bigint,
  'email' : string,
  'address' : string,
  'saleCommission' : bigint,
  'expectedPrice' : bigint,
  'expectedRent' : bigint,
  'dealType' : string,
}
export interface SiteVisit {
  'id' : bigint,
  'contact' : string,
  'clientName' : string,
  'visitDate' : string,
  'propertyId' : bigint,
  'requirementType' : string,
  'budget' : bigint,
  'remarks' : string,
}
export interface _SERVICE {
  'addInventoryChecklist' : ActorMethod<[InventoryChecklist], bigint>,
  'addInvoice' : ActorMethod<[Invoice], string>,
  'addProperty' : ActorMethod<[Property], bigint>,
  'addSiteVisit' : ActorMethod<[SiteVisit], bigint>,
  'deleteInventoryChecklist' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'deleteSiteVisit' : ActorMethod<[bigint], undefined>,
  'getAllInventoryChecklists' : ActorMethod<[], Array<InventoryChecklist>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getAllSiteVisits' : ActorMethod<[], Array<SiteVisit>>,
  'getDefaultChecklistItems' : ActorMethod<[], Array<Item>>,
  'getInventoryChecklist' : ActorMethod<[bigint], InventoryChecklist>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getProperty' : ActorMethod<[bigint], Property>,
  'getSiteVisit' : ActorMethod<[bigint], SiteVisit>,
  'updateInventoryChecklist' : ActorMethod<[InventoryChecklist], undefined>,
  'updateInvoice' : ActorMethod<[Invoice], undefined>,
  'updateProperty' : ActorMethod<[Property], undefined>,
  'updateSiteVisit' : ActorMethod<[SiteVisit], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];