/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Property {
    id: bigint;
    title: string;
    contact: string;
    ownerName: string;
    propertyType: string;
    rentCommission: bigint;
    city: string;
    deposit: bigint;
    email: string;
    address: string;
    saleCommission: bigint;
    expectedPrice: bigint;
    expectedRent: bigint;
    dealType: string;
}
export interface InventoryChecklist {
    id: bigint;
    ownerName: string;
    date: string;
    propertyId: bigint;
    tenantName: string;
    items: Array<Item>;
}
export interface Item {
    qty: bigint;
    itemName: string;
    remarks: string;
    condition: string;
}
export interface Invoice {
    id: bigint;
    status: string;
    clientName: string;
    date: string;
    description: string;
    propertyId: bigint;
    invoiceNumber: string;
    paymentMode: string;
    amount: bigint;
}
export interface SiteVisit {
    id: bigint;
    contact: string;
    clientName: string;
    visitDate: string;
    propertyId: bigint;
    requirementType: string;
    budget: bigint;
    remarks: string;
}
export interface backendInterface {
    addInventoryChecklist(checklist: InventoryChecklist): Promise<bigint>;
    addInvoice(invoice: Invoice): Promise<string>;
    addProperty(property: Property): Promise<bigint>;
    addSiteVisit(siteVisit: SiteVisit): Promise<bigint>;
    deleteInventoryChecklist(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deleteProperty(id: bigint): Promise<void>;
    deleteSiteVisit(id: bigint): Promise<void>;
    getAllInventoryChecklists(): Promise<Array<InventoryChecklist>>;
    getAllInvoices(): Promise<Array<Invoice>>;
    getAllProperties(): Promise<Array<Property>>;
    getAllSiteVisits(): Promise<Array<SiteVisit>>;
    getDefaultChecklistItems(): Promise<Array<Item>>;
    getInventoryChecklist(id: bigint): Promise<InventoryChecklist>;
    getInvoice(id: bigint): Promise<Invoice>;
    getProperty(id: bigint): Promise<Property>;
    getSiteVisit(id: bigint): Promise<SiteVisit>;
    updateInventoryChecklist(checklist: InventoryChecklist): Promise<void>;
    updateInvoice(invoice: Invoice): Promise<void>;
    updateProperty(property: Property): Promise<void>;
    updateSiteVisit(siteVisit: SiteVisit): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addInventoryChecklist(arg0: InventoryChecklist): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryChecklist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryChecklist(arg0);
            return result;
        }
    }
    async addInvoice(arg0: Invoice): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvoice(arg0);
            return result;
        }
    }
    async addProperty(arg0: Property): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(arg0);
            return result;
        }
    }
    async addSiteVisit(arg0: SiteVisit): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSiteVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSiteVisit(arg0);
            return result;
        }
    }
    async deleteInventoryChecklist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.deleteInventoryChecklist(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.deleteInventoryChecklist(arg0);
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.deleteInvoice(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.deleteInvoice(arg0);
        }
    }
    async deleteProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.deleteProperty(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.deleteProperty(arg0);
        }
    }
    async deleteSiteVisit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.deleteSiteVisit(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.deleteSiteVisit(arg0);
        }
    }
    async getAllInventoryChecklists(): Promise<Array<InventoryChecklist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryChecklists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryChecklists();
            return result;
        }
    }
    async getAllInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInvoices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInvoices();
            return result;
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return result;
        }
    }
    async getAllSiteVisits(): Promise<Array<SiteVisit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSiteVisits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSiteVisits();
            return result;
        }
    }
    async getDefaultChecklistItems(): Promise<Array<Item>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDefaultChecklistItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDefaultChecklistItems();
            return result;
        }
    }
    async getInventoryChecklist(arg0: bigint): Promise<InventoryChecklist> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryChecklist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryChecklist(arg0);
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return result;
        }
    }
    async getProperty(arg0: bigint): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return result;
        }
    }
    async getSiteVisit(arg0: bigint): Promise<SiteVisit> {
        if (this.processError) {
            try {
                const result = await this.actor.getSiteVisit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSiteVisit(arg0);
            return result;
        }
    }
    async updateInventoryChecklist(arg0: InventoryChecklist): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateInventoryChecklist(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.updateInventoryChecklist(arg0);
        }
    }
    async updateInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateInvoice(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.updateInvoice(arg0);
        }
    }
    async updateProperty(arg0: Property): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateProperty(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.updateProperty(arg0);
        }
    }
    async updateSiteVisit(arg0: SiteVisit): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.updateSiteVisit(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.updateSiteVisit(arg0);
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
